### ISSUE TITLE
Backup boolean not adjustable

### ISSUE THREAD

**Issue by JKetelaar** [nginxinc/ansible-role-nginx-config#111]
### Describe the bug
All template calls use `backup: yes`, for example: https://github.com/nginxinc/ansible-role-nginx-config/blob/4269a228dbc557c5b8aa6942f188d5e43a958a4c/tasks/config/template-config.yml#L41
This creates a lot of backup files once the role has run.

### To reproduce
1. Deploy NGINX Config role
2. Deploy NGINX Config role again
3. Check the `/etc/nginx/conf.d/` directory for example; this will have a lot of backup files

### Expected behavior
While having backup files is fine, it should be opt-out

Is this expected behavior? Or would you like an option where this is set from a var(iable)?

**Comment by alessfg** [comment]
That is the expected behaviour. That being said, I'm open to making it customisable so that people can opt-out of the backup feature.

**Comment by JKetelaar** [comment]
Wonderful, I'll work on that!
