### ISSUE TITLE
Add server_names_hash_bucket_size config setting in nginx.conf template

### ISSUE THREAD

**Issue by fschueller** [nginxinc/ansible-role-nginx-config#113]
👋 Hello! I'd like to submit a feature request/discussion.

### Problem
Today when provisioning one of my NGINX servers, it directed me to increase the [server_names_hash_bucket_size](https://nginx.org/en/docs/http/ngx_http_core_module.html#server_names_hash_bucket_size) to 64. This presumably happens when the individual servers have long names/domains. 
I'm configuring my NGINX configs with this role, but I didn't find a value [in the template](https://github.com/nginxinc/ansible-role-nginx-config/blob/main/templates/nginx.conf.j2) for this setting.

### Solution
Include the setting in this role.

### Describe alternatives you've considered
Manual patching or provisioning of the config.

### Additional context
Error returned from Ansible on server restart:
<img width="1157" alt="Screenshot 2021-04-23 at 17 08 49" src="https://user-images.githubusercontent.com/11717425/115891823-d0abe100-a456-11eb-862d-84b1c506a673.png">

I could potentially also help with implementing this feature.
Thanks for replying and especially for maintaining this project! 👏

**Comment by alessfg** [comment]
That is a great suggestion! Feel free to open a PR if you want to take a stab at it 😄
