### ISSUE TITLE
Molecule: Installation of NGINX Plus failing on all configured distributions

### ISSUE THREAD

**Issue by fschueller** [nginxinc/ansible-role-nginx-config#115]
### Describe the bug
While running the molecule tests, the installation of NGINX Plus is failing.

<img width="1790" alt="Screenshot 2021-04-28 at 09 46 29" src="https://user-images.githubusercontent.com/11717425/116366749-eaf30f80-a806-11eb-89aa-82ded94f04ee.png">

### To reproduce
1. Checkout the repository on `main`
2. Run `molecule test --all`
3. See above error.

### Expected behavior
All tests passing

### Your environment:
-   NGINX Config Role on `main`, commit `797232e0dbef01c0ce21ea3bd5ba48d26094df5e`
-   ansible 2.10.8
-   molecule 3.3.0 using python 3.9
-   MacOS 11.2.3

### Additional context
I found this while testing my contribution. As it is happening on `main` too, I don't see this related to my changes. If you think this is an edge case related to my own setup, please don't feel compelled to process this.

**Comment by alessfg** [comment]
Ah right, the NGINX Plus test requires you to have an NGINX Plus license (trial licenses should be fine). That being said, I do not expect nor want people to go through the trial license process unless you are specifically working on something unique to NGINX Plus. I'll update the contribution guidelines to make a note about this.
