### ISSUE TITLE
'Remove NGINX Configuration Files' step failing

### ISSUE THREAD

**Issue by Migsi** [nginxinc/ansible-role-nginx-config#15]
**Describe the bug**
The nginx role fails on "(Setup: All OSs) Remove NGINX Configuration Files" with the given error message:
`fatal: [playground.example.com]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{ nginx_config_files.results | default('') | map(attribute='files') | sum(start=[]) | map(attribute='path') | list + nginx_cleanup_config_files | default('') }}): can only concatenate list (not \"str\") to list"
}`

**To reproduce**
1. Deploy NGINX role using playbook.yml (configured to setup a reverse proxy only; does not seem to be the root cause though)
2. Waiting for the "(Setup: All OSs) Remove NGINX Configuration Files" step to be executed
3. See error

**Expected behavior**
The role proceeds through this step as always and does not stall provisioning.

**Your environment:**
-   nginxinc.nginx (0.15.0)
-   ansible 2.9.6
-   ubuntu server 18.04.5 LTS

**Additional context**
I'm not sure if it helps, but the machine executing the playbook is running ubuntu 20.04 LTS. The role was working flawless until my recent (1 day ago) --force install of all galaxy obtained roles.

**Comment by alessfg** [comment]
Hey @Migsi! Tests for this parameter are passing just fine. Can you have a look at the test playbook and see if there's anything that you might be missing? https://github.com/nginxinc/ansible-role-nginx-config/blob/main/molecule/common/playbooks/module_converge.yml#L11-L17

**Comment by dudefellah** [comment]
I might be seeing the same issue on the 0.1.0 release of this role. I don't see any changes since that release that looks like they would affect this behaviour, so I'm guessing it's still a problem.

The problem is that this happens when I'm not explicitly setting `nginx_config_cleanup_files` in my play:

```
TASK [nginxinc.nginx_config : (Setup: All OSs) Remove NGINX Configuration Files] ***********************************************************************************************************************************
fatal: [prod.hla.triumf.ca]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ nginx_config_files.results | default('') | map(attribute='files') | sum(start=[]) | map(attribute='path') | list + nginx_config_cleanup_files | default('') }}): can only concatenate list (not \"str\") to list"}
```

It looks like `nginx_config_cleanup_files` is assumed to be a str instead of a list, which messed up the list addition. This value also happens to be commented out in `defaults/main/main.yml`, so defaulting it to an empty list for the role should probably solve it.

**Comment by Migsi** [comment]
> I might be seeing the same issue on the 0.1.0 release of this role. I don't see any changes since that release that looks like they would affect this behaviour, so I'm guessing it's still a problem.
> 
> The problem is that this happens when I'm not explicitly setting `nginx_config_cleanup_files` in my play:
> 
> ```
> TASK [nginxinc.nginx_config : (Setup: All OSs) Remove NGINX Configuration Files] ***********************************************************************************************************************************
> fatal: [prod.hla.triumf.ca]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{ nginx_config_files.results | default('') | map(attribute='files') | sum(start=[]) | map(attribute='path') | list + nginx_config_cleanup_files | default('') }}): can only concatenate list (not \"str\") to list"}
> ```
> 
> It looks like `nginx_config_cleanup_files` is assumed to be a str instead of a list, which messed up the list addition. This value also happens to be commented out in `defaults/main/main.yml`, so defaulting it to an empty list for the role should probably solve it.

This seems to nail it. Anyways, I still have to migrate my existing config to the new naming schema that was introduced by the split. That was causing the issue at my side, since `nginx_config_cleanup_files` was never part of my config.

**Comment by alessfg** [comment]
Alright, I'll look into this once I fix some permission issues introduced in Ansible 2.9.12
