### ISSUE TITLE
How to omit  load_module: modules/ngx_http_js_module.so

### ISSUE THREAD

**Issue by palansher** [nginxinc/ansible-role-nginx-config#251]
Good day!

In your file "defaults/main/template.yml" there is "load_module"  list :

nginx_config_main_template:
  config:
    main: 
      load_module: modules/ngx_http_js_module.so

In my nginx configuration, there is no real file "ngx_http_js_module.so" in file system.
So I have error during role run.

I don't want to change your role files by removing "load_module: modules" element from dictionary.

How can I disable/omit this step in playbook ? Probably by re-setting "load_module" variable  for "empty/undefined" value  in playbook. To avoid such errors.

Thank you for your work for community!

BTW: do you have the support for sites-available/sites-enabled config file structure?

**Comment by alessfg** [comment]
You can comment out that line and that should do the trick! I will open a PR to comment it out too given that it is not found in the default NGINX install config. That line must have somehow slipped through 😅

**Comment by palansher** [comment]
For a while - this strange magic in playbook, that I don't even understand, did the trick - no error message or template problems.
```
config:
              main: # Configure NGINX main core directives
                  load_module: "{{ omit }}"
```

Will wait your more solid resolution :)

Thanks!

**Comment by alessfg** [comment]
Try pulling the latest commit from here and lmk if it works better now! #252 should have disabled the `load_module` directive as a default.
