### ISSUE TITLE
Add `include` support in default.conf.j2 template

### ISSUE THREAD

**Issue by Al-thi** [nginxinc/ansible-role-nginx-config#283]
### Is your feature request related to a problem? Please describe

It seems impossible to use the `include` ([doc](https://nginx.org/en/docs/ngx_core_module.html#include)) directive directly in `nginx.conf` (aka using `nginx_config_main_template` with `default.conf.j2`), which is sad because of Debian's `/etc/nginx/modules-available/` and `/etc/nginx/modules-enabled/` directories.

I always had a `nginx.conf` like this :
```
xxx

include /etc/nginx/modules-enabled/*.conf;

events {
        xxx
}

http {
        include /etc/nginx/mime.types;

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}
```

### Describe the solution you'd like

I'd like to add support to the `include` keyword in `default.conf.j2`.

### Describe alternatives you've considered

I tried to use `include /etc/nginx/modules-enabled/*.conf;` directly in `http` config (aka inside `nginx_config_http_template`), but the load_modules directive can't be used inside `http` entries, so that's not possible.

I currently list all my modules like this :
```sh
# cat modules-enabled/*
load_module modules/ngx_http_auth_pam_module.so;
load_module modules/ngx_http_dav_ext_module.so;
load_module modules/ngx_http_echo_module.so;
load_module modules/ngx_http_geoip_module.so;
load_module modules/ngx_http_image_filter_module.so;
load_module modules/ngx_http_subs_filter_module.so;
load_module modules/ngx_http_upstream_fair_module.so;
load_module modules/ngx_http_xslt_filter_module.so;
load_module modules/ngx_mail_module.so;
load_module modules/ngx_stream_module.so;
```
And then list all modules inside of the `load_module` directive :
```yaml
load_module:
        - modules/ngx_http_auth_pam_module.so
        - modules/ngx_http_dav_ext_module.so
        - modules/ngx_http_echo_module.so
        - modules/ngx_http_geoip_module.so
        - modules/ngx_http_image_filter_module.so
        - modules/ngx_http_subs_filter_module.so
        - modules/ngx_http_upstream_fair_module.so
        - modules/ngx_http_xslt_filter_module.so
        - modules/ngx_mail_module.so
        - modules/ngx_stream_module.so
```

But I lose the possibility to remove symlinks in `modules-enabled` + restart nginx for disabling a module.

### Additional context

N/A

PS : Thanks for this amazing role !

**Comment by alessfg** [comment]
It took a while, but I've finally had time to work on this. #302 should allow you to achieve your use case! 😄
