### ISSUE TITLE
Role should restart/reload Nginx when SSL certificates change

### ISSUE THREAD

**Issue by Chippit** [nginxinc/ansible-role-nginx-config#318]
### Describe the bug

When running the role in an already-deployed environment with no change but an updated certificate, executing the role does not restart Nginx.

### To reproduce

1. Deploy the Ansible NGINX configuration onto a host, with SSL keys (`nginx_config_upload_ssl_enable: true`, etc.)
2. Update the source SSL keys on the Ansible Controller
3. Run your playbook again

### Expected behavior

Nginx restarts and presents the new SSL keys.

### Your environment

- Ansible 2.12.5
- Ansible Nginx 0.24.0
- Ansible Nginx Config 0.6.0

**Comment by jcox10** [comment]
I just ran into this issue also, there is no handler when the SSL cert or key files are changed.

**Comment by alessfg** [comment]
I will admit this is a use case I did not test and as such is indeed likely to be broken. I will try to get a fix in as soon as I can!

**Comment by jcox10** [comment]
I just submitted a PR that fixes this issue
