### ISSUE TITLE
Handler - NGINX Config fails in check mode

### ISSUE THREAD

**Issue by gnalsa** [nginxinc/ansible-role-nginx-config#32]
**Describe the bug**
When running ansible-playbook --check (or -C) there is an error reporting `config` dict has no attribute `rc`

``` text
FAILED! => {"msg": "The conditional check 'config.rc != 0' failed. The error was: error while evaluating conditional (config.rc != 0): 'dict object' has no attribute 'rc'\n\nThe error appears to be in '/Users/<myname>/.ansible/roles/nginxinc.nginx_config/handlers/main.yml': line 9, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: (Handler - NGINX Config) Print NGINX error if syntax check fails\n  ^ here\n"}
```

This section of code will always fail in check mode, because the task `(Handler - NGINX Config) Check NGINX` is skipped and `config.rc` will never exist.

``` text
- name: (Handler - NGINX Config) Check NGINX
  command: nginx -t
  register: config
  ignore_errors: yes
  changed_when: false
  listen: (Handler - NGINX Config) Run NGINX

- name: (Handler - NGINX Config) Print NGINX error if syntax check fails
  debug:
    var: config.stderr_lines
  failed_when: config.rc != 0
  when: config.rc != 0
  listen: (Handler - NGINX Config) Run NGINX
```

**Comment by gnalsa** [comment]
Here are a couple of solutions I could think of, but not sure if this would break some other behavior.

1) listen to check nginx instead of run nginx
``` text
diff --git a/handlers/main.yml b/handlers/main.yml
index 94508ba..25330b9 100644
--- a/handlers/main.yml
+++ b/handlers/main.yml
@@ -11,7 +11,7 @@
     var: config.stderr_lines
   failed_when: config.rc != 0
   when: config.rc != 0
-  listen: (Handler - NGINX Config) Run NGINX
+  listen: (Handler - NGINX Config) Check NGINX

 - name: (Handler - NGINX Config) Start/reload NGINX
   service:
```
2) add conditional to not run in check mode
``` text
diff --git a/handlers/main.yml b/handlers/main.yml
index 94508ba..5d97b17 100644
--- a/handlers/main.yml
+++ b/handlers/main.yml
@@ -9,8 +9,10 @@
 - name: (Handler - NGINX Config) Print NGINX error if syntax check fails
   debug:
     var: config.stderr_lines
-  failed_when: config.rc != 0
-  when: config.rc != 0
+  failed_when: config.rc != 0
+  when:
+    - config.rc != 0
+    - not ansible_check_mode | bool
   listen: (Handler - NGINX Config) Run NGINX

 - name: (Handler - NGINX Config) Start/reload NGINX
```

**Comment by gnalsa** [comment]
It also might be considered to take on the bigger task of actually validating the configuration in check mode, but this seems much more complex.

**Comment by alessfg** [comment]
Right. Option 2 looks fine to me (I think handler's might get a bit messy if we follow option 1), but what about setting up `check_mode: no` on the `Check NGINX` handler?

**Comment by gnalsa** [comment]
Yes, I think that makes sense with the current implementation. It might be worth noting in the documentation that configuration check cannot be performed in ansible check mode.

I think it would be a common feature request to have configuration validation working in check mode though.

**Comment by alessfg** [comment]
By setting `check_mode: no` the task should always be run, even when using check mode. Unless I am missing something? https://docs.ansible.com/ansible/latest/user_guide/playbooks_checkmode.html#enforcing-or-preventing-check-mode-on-tasks

**Comment by gnalsa** [comment]
You are correct. This is my suggestion in solution 2. I am using same syntax from other task `Start/reload NGINX`

``` text
- name: (Handler - NGINX Config) Start/reload NGINX
  service:
    name: nginx
    state: reloaded
  when:
    - nginx_config_start | bool
    - not ansible_check_mode | bool
  listen: (Handler - NGINX Config) Run NGINX
```

I will open a second ticket as feature request for the following: Add support to validate nginx configuration in check mode.
This feature would be non-trivial and may not even be possible, but would be a big help in preventing bad configuration pushes.

**Comment by alessfg** [comment]
If you set `not ansible_check_mode | bool` then the `Check NGINX` handler will get skipped on check mode, but if you set `check_mode: no`, it will always run on check mode. I'm going to open a PR to add the latter functionality since it makes more sense to run `Check NGINX` always.

**Comment by alessfg** [comment]
Quick update, implementing what I mentioned above successfully turned out to be not as trivial as I expected. I have what I think might be a workable solution but I still need to do some testing. PR hopefully coming in early next week.

This still will not validate the NGINX config that you are deploying in the given playbook (as you mentioned, it might not even be possible within Ansible's check mode), but at least it should cover any unexpected failures when using check.
