### ISSUE TITLE
How to set "global" variables in the HTTP context

### ISSUE THREAD

**Issue by tibz7** [nginxinc/ansible-role-nginx-config#322]
### Describe the bug

It is not possible to set variable in the `HTTP` block while according to the default variables, it should:
`server_names_hash_bucket_size: 32  # Available only in the 'http' context`

### To reproduce
add `server_names_hash_bucket_size` in `nginx_config_main_template.config.http`

### Expected behavior
The settings is added.

Looking at the defaults, it was or should be possible, but it is not. Maybe the documentation is just miss leading?
Otherwise It would be even better if the options  settables in `core` (gzip, access log format, sendfile,etc...) could be set in the `http` block as well, as behave as defaults for all the virtual servers.

**Comment by tibz7** [comment]
yes thats right, but I understood the `http context` as being the one `http` in `nginx.conf`.  I use the `nginx_config_http_template` for the virtual hosts.
I'm looking for a way to add there variables such as `gzip` or `server_names_hash_bucket_size` that would be common to all my virtual servers.
I would like my `nginx.conf` to look like that 
```
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
	worker_connections 2048;
}

http {

	sendfile on;
	aio threads;
	tcp_nopush on; 
        ...
```


But it seems to me that this is impossible at the moment. the only way would be that I write my own template in order to support these settings, which is a bit sad as all the other options are existing within the nginx_config_http_template

**Comment by alessfg** [comment]
You could include a generic `http` config file using the `nginx_config_http_template` with all these settings and include it within the `http` context in your `nginx_config_main_template`? If you use top level directives these should then be shared across all your various server blocks/config files.

**Comment by tibz7** [comment]
ah yes that seems to be a working option. thank you!
