### ISSUE TITLE
Missing support for the ip_hash directive in upstream blocks

### ISSUE THREAD

**Issue by dunielpls** [nginxinc/ansible-role-nginx-config#37]
**Is your feature request related to a problem? Please describe.**
The playbook I am developing using this role requires the use of `ip_hash` in `upstream {}` blocks. It does not currently seem to be supported.

**Describe the solution you'd like**
I would like to have support for the `ip_hash` directive added to the `http/default.conf.j2` template. I may open a PR myself to fix this issue given enough spare time.

**Describe alternatives you've considered**
I have considered manually copying and altering the template file [default.conf.j2](templates/http/default.conf.j2) but decided it would be best if this is fixed upstream.

**Additional context**
Example:
```nginx
upstream some_name {
    ip_hash;
    server 10.10.10.10;
    server 10.20.20.20;
}
```

Note: I erroneously submitted the template issue by accident after changing the issue type.

**Comment by alessfg** [comment]
You should be able to set `ip_hash` by doing something like
```
upstreams:
  frontend_upstream:
    name: frontend_servers
    lb_method: ip_hash
```

**Comment by dunielpls** [comment]
> You should be able to set `ip_hash` by doing something like
> 
> ```
> upstreams:
>   frontend_upstream:
>     name: frontend_servers
>     lb_method: ip_hash
> ```

That's a pretty good workaround, thank you.
