### ISSUE TITLE
Logrotate does not format correctly 

### ISSUE THREAD

**Issue by tibz7** [nginxinc/ansible-role-nginx-config#381]
### Describe the bug

The logrotate is not correclty formatted

### To reproduce

it looks like that when deployed 

``` 
/var/log/nginx/*.log
{
    d
    a
    i
    l
    y
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}
```

### Expected behavior

```
/var/log/nginx/*.log
{
    daily
    postrotate
        if [ -f /var/run/nginx.pid ]; then
            kill -USR1 `cat /var/run/nginx.pid`
        fi
    endscript
}
```

### Your environment

debian 12

**Comment by alessfg** [comment]
This role does not configure logrotate. Are you perhaps using the main [Ansible NGINX role](https://github.com/nginxinc/ansible-role-nginx) (https://github.com/nginxinc/ansible-role-nginx) instead? Otherwise, are you maybe using a different role or task to configure logrotate?

**Comment by alessfg** [comment]
See https://github.com/nginxinc/ansible-role-nginx/issues/672
