### ISSUE TITLE
[Question/Feature] template gzip on nginx.conf.j2 

### ISSUE THREAD

**Issue by xonvanetta** [nginxinc/ansible-role-nginx-config#42]
**Is your feature request related to a problem? Please describe.**
My problem was i wanted a way to enable gzip with some options on the default nginx.conf that this playbook creates but ididn't find such an option or something that i could do with the default nginx.conf except copy and add my own gzip headers/options.

**Describe the solution you'd like**
Adding a template option to enable gzip without creating a custom nginx.conf.j2 template. 

**Workaround**
Creating my own nginx.conf that kinda has gzip enabled with some modifications.

Its not really a great deal but would ofcourse be a nice feature.
Here a bit of templated code i did really as an example
```
{% if nginx_config_main_template.http_settings.gzip %}
    gzip on;
{% if nginx_config_main_template.http_settings.gzip.vary %}
    gzip_vary on;
{% endif %}
{% if nginx_config_main_template.http_settings.gzip.min_length %}
    gzip_min_length {{ nginx_config_main_template.http_settings.gzip.min_length }};
{% endif %}
{% if nginx_config_main_template.http_settings.gzip.proxied is defined and nginx_config_main_template.http_settings.gzip.proxied | length %}
    gzip_proxied {{ nginx_config_main_template.http_settings.gzip.proxied }};
{% endif %}
{% if nginx_config_main_template.http_settings.gzip.types is defined and nginx_config_main_template.http_settings.gzip.types | length %}
    gzip_types {{ nginx_config_main_template.http_settings.gzip.types }};
{% endif %}
{% if nginx_config_main_template.http_settings.gzip.disable %}
    gzip_disable {{ nginx_config_main_template.http_settings.gzip.disable }}
{% endif %}
{% else %}
	#gzip on;
{% endif %}
```

**Comment by alessfg** [comment]
Until this gets implemented, have you had a look at the `custom_options` variable?

**Comment by xonvanetta** [comment]
Ahh no, missed that option totally, but it should work with my case. But the thing was i just need gzip temporary for some days

I must have missed the `custom_options` when i gazed through the documentation
