### ISSUE TITLE
https_redirect has inconsitant type in the template.

### ISSUE THREAD

**Issue by jlec** [nginxinc/ansible-role-nginx-config#43]
**Describe the bug**
The following code is not working. https_redirect is a boolean in the check, but needs to be a string for the config template

```
{% if item.value.servers[server].https_redirect is defined and item.value.servers[server].https_redirect %}
    return 301 https://{{ item.value.servers[server].https_redirect }}$request_uri;
{% endif %}
```

**Comment by alessfg** [comment]
Heya! I just tested this on my end and it's working fine. It's not the best implementation, but the boolean check evaluates to true when the value contains a string that doesn't map to a boolean value. That being said all those checks will be refactored as part of an upcoming templating refactor (no ETA for it yet).

**Comment by jlec** [comment]
I am ending up with

```
return 301 https://True$request_uri;
```

**Comment by alessfg** [comment]
What value are you using for the `https_redirect` variable? (Feel free to slightly censor if necessary.)

**Comment by jlec** [comment]
I set it to `yes`

**Comment by jlec** [comment]
The vaiable susggest that you will get a redirect to https

**Comment by jlec** [comment]
this works
```
 94             servers:
 95               redirect:
 96                 listen:
 97                   listen_redirect:
 98                     port: 80
 99                     https_redirect: $host
```

**Comment by alessfg** [comment]
Right. Might be worth adding a better comment/explanation as to how it actually works. As it turns out (and you rightfully deduced), it does not actually do a simple HTTPS redirect. You have to specify the URI you want to redirect too.

**Comment by jlec** [comment]
In your jinja code you can drop the second half if it doesn't expect a boolean. _is defined _ should be enough

**Comment by Alex-Giaquinto** [comment]
@alessfg sorry to bother you and re-open this thread, could you by any chance point out how to do this with the new template. Just trying to set a permanent redirect (return 301) from 80->443 and having some trouble. Thanks!

**Comment by alessfg** [comment]
You would use something along the lines of https://github.com/nginxinc/ansible-role-nginx-config/blob/main/molecule/default/converge.yml#L660-L664, but instead of using the `text` parameter, you'd use the `url` parameter https://github.com/nginxinc/ansible-role-nginx-config/blob/main/defaults/main/template.yml#L669.

Sadly I don't have time to test a working example right now, but that should hopefully get you on the right path before I would be able to test an example myself.
