### ISSUE TITLE
SELinux state is changed from "enforcing" to "permissive" when nginx_config_selinux: true 

### ISSUE THREAD

**Issue by hakamine** [nginxinc/ansible-role-nginx-config#46]
**Describe the bug**
On a target host with SELinux state `enforcing`, running the role with `nginx_config_selinux: true` sets the target host SELinux state to `permissive`

**To reproduce**
1. On a target host with SELinux state set to `enforcing` (used a CentOS 7 host as target), deploy NGINX Config role using `nginx_config_selinux: true` ( note: the role variable `nginx_config_selinux_enforcing` was unchanged from the role default (true))
2. After the role completes check SELinux state with `getenforce` command. It returned `Permissive`

**Expected behavior**
Expected SELinux state to remain `enforcing`

**Your environment:**
-  current main branch (commit d0c6ab13)
-  Ansible 2.9.11
-   Target deployment platform: CentOS 7.8.2003 (Digital Ocean droplet)

**Additional context**
Excerpt from playbook output (-v): 
```
TASK [external-roles/nginxinc.nginx-config : Set SELinux mode to permissive] ***********************
ok: [targethost] => changed=false
  configfile: /etc/selinux/config
  msg: SELinux state changed from 'enforcing' to 'permissive', Config SELinux state changed from 'enforcing' to 'permissive'
  policy: targeted
  reboot_required: false
  state: permissive

...
...
TASK [external-roles/nginxinc.nginx-config : Set SELinux mode to enforcing] ************************
skipping: [targethost] => changed=false
  skip_reason: Conditional result was False
```

**Comment by hakamine** [comment]
I was trying to understand the logic of [setup-selinux.yml](https://github.com/nginxinc/ansible-role-nginx-config/blob/d0c6ab131f5549dd01b474bbee73f50a42676245/tasks/prerequisites/setup-selinux.yml):

- I don't understand why [the task that changes state to `permissive`](https://github.com/nginxinc/ansible-role-nginx-config/blob/d0c6ab131f5549dd01b474bbee73f50a42676245/tasks/prerequisites/setup-selinux.yml#L20-L25) is needed even when `nginx_config_selinux_enforcing` is `true`   (temporarily set state to permissive to prevent any potential failures while SELinux is being configured?). 

- It looks like the second condition of [the task that sets SELinux state to `enforcing`](https://github.com/nginxinc/ansible-role-nginx-config/blob/d0c6ab131f5549dd01b474bbee73f50a42676245/tasks/prerequisites/setup-selinux.yml#L71-L78) may not be met because ansible facts (which were gathered at the beginning of the playbook run) returns`enforcing` despite the actual SELinux mode of the target being  `permissive` at the time the task is evaluating the conditional

**Comment by alessfg** [comment]
> * I don't understand why [the task that changes state to `permissive`](https://github.com/nginxinc/ansible-role-nginx-config/blob/d0c6ab131f5549dd01b474bbee73f50a42676245/tasks/prerequisites/setup-selinux.yml#L20-L25) is needed even when `nginx_config_selinux_enforcing` is `true`   (temporarily set state to permissive to prevent any potential failures while SELinux is being configured?).

Yep pretty much.

> * It looks like the second condition of [the task that sets SELinux state to `enforcing`](https://github.com/nginxinc/ansible-role-nginx-config/blob/d0c6ab131f5549dd01b474bbee73f50a42676245/tasks/prerequisites/setup-selinux.yml#L71-L78) may not be met because ansible facts (which were gathered at the beginning of the playbook run) returns`enforcing` despite the actual SELinux mode of the target being  `permissive` at the time the task is evaluating the conditional

You are right, I missed that gather facts only runs at launch. I'll have a fix in place shortly.
