### ISSUE TITLE
"Ensure NGINX proxy cache directories exist" fails despite skip_missing flag

### ISSUE THREAD

**Issue by tux-o-matic** [nginxinc/ansible-role-nginx-config#47]
**Describe the bug**
Role fails when hitting ``` Ensure NGINX proxy cache directories exist```task despite ```skip_missing: true```.

**To reproduce**
1. Deploy NGINX Config role using playbook.yml
2. Create your own ```nginx_config_http_template```, without any proxy_cache
3. See error:
```json
{"msg": "subelements lookup expects a dictionary, got 'None'"}
```

**Expected behavior**
The role shouldn't fail on cache directory check when proxy cache isn't configured/used.

**Your environment:**
-   Version of the NGINX Config role: 0.3.0
-   Version of Ansible: 2.9.9
-   Target deployment platform: RHEL 7.9

**Comment by alessfg** [comment]
I can't reproduce this issue myself, can you share a censored version of your playbook?

**Comment by tux-o-matic** [comment]
Hi @alessfg , isn't the ```{"msg": "subelements lookup expects a dictionary, got 'None'"}```error a sign that it doesn't skip or fail silently on this task like it should when proxy cache isn't set?

**Comment by tux-o-matic** [comment]
I believe I nailed down the issue to an empty server block. That's not a valid configuration anyway so closing the issue.
