### ISSUE TITLE
proxy_set_header is singular but we have proxy_hide_headers

### ISSUE THREAD

**Issue by tux-o-matic** [nginxinc/ansible-role-nginx-config#51]
**Is your feature request related to a problem? Please describe.**
The default template should use plural variable name when dealing with proxy_set_header and proxy_hide_heaader.
Today, there is *proxy_hide_headers* and *proxy_set_header*
Even though one uses hash and the other is a simple array, it should be expressed as plural rabble names. 

**Describe the solution you'd like**
We should lookup for ```proxy_set_headers``` in the [template](https://github.com/nginxinc/ansible-role-nginx-config/blob/6e7839f2aab33983dea06fa34a29a30add56f716/templates/http/default.conf.j2#L286) and the [defaults](https://github.com/nginxinc/ansible-role-nginx-config/blob/710efa69b99101caaa360bfcddd5e45409f5e81b/defaults/main/template.yml#L232)

**Comment by alessfg** [comment]
Finally have time to address this. However, I am going to rename `proxy_hide_headers` to `proxy_hide_header` to stay inline with NGINX directive names.

**Comment by alessfg** [comment]
Moving to the 0.4.0 release since this is going to result in a breaking change.
