### ISSUE TITLE
Undo main nginx.conf changes

### ISSUE THREAD

**Issue by rolandjitsu** [nginxinc/ansible-role-nginx-config#6]
**Is your feature request related to a problem? Please describe.**
Is there any way to undo any changes done to the main `nginx.conf` (go back to original)? I was testing the `nginx_main_template` options as I couldn't get port 80 to run my app, but I later discovered that using `default_server` for listen opts will also work.

But now, I'm not sure how to undo all of those changes.

**Describe the solution you'd like**
I should be able to restore the original `nginx.conf`.

**Describe alternatives you've considered**
I can live with the current conf, but I don't like all the vars I have set just to be able to run the app on port 80.

**Additional context**
No additional context.

**Comment by alessfg** [comment]
Sorry for the extra delay dealing with this! I have an idea on how to achieve this but it might have to wait until an upcoming templating refactor gets finished.

**Comment by alessfg** [comment]
As of the latest release, if you run the role with `nginx_config_main_template_enable` set to true but leave the `nginx_config_main_template` defaults, you should be able to recreate a close to the default original `nginx.conf` file. I think that's good enough?

**Comment by alessfg** [comment]
Closing this for the time being since I think the current solution is pretty close to the original intent of this issue. Feel free to reopen the issue if that's not the case! 😄
