### ISSUE TITLE
Allow simple rewriting

### ISSUE THREAD

**Issue by rgarrigue** [nginxinc/ansible-role-nginx-config#9]
**Is your feature request related to a problem? Please describe.**

I painfully came up with a raw nginx conf for a simple old domain / uri scheme to new one

```
 server {
     listen 0.0.0.0:80;
     server_name documentation.old.domain;
     rewrite (.*).html(.*) $1$2;
     rewrite (.*)/en/stable(.*) $1$2;
     return 301 https://new.domain/uc-doc$uri;
 }
```

I can't implement this one.

**Describe the solution you'd like**

Something that work. Outside of a homemade raw Ansible `copy:`

**Describe alternatives you've considered**

Tried quickly, ended up with this mess that's never gonna work with the rewrite after the proxy pass (or so I believe)

```
    listen 0.0.0.0:80;
    server_name documentation.old.domain;
    location ^ {
        proxy_pass https://new.domain/uc-doc;
        rewrite rewrite (.*).html(.*) $1$2;;
        rewrite rewrite (.*)/en/stable(.*) $1$2;;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
```

**Comment by alessfg** [comment]
@rgarrigue do you by any chance have a copy or remember the playbook you were using when you got the configuration mentioned in the original issue?

**Comment by alessfg** [comment]
I added a test to check whether the rewrite variable was working correctly and it looks like it is? 🤷‍♂️
Closing this for the time being, but feel free to reopen the issue if you think I'm missing something.
